apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
