apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-sealedsecret
  namespace: rmz2
spec:
  encryptedData:
    mysecret: AgAnvaWegGELNftMPNcucSRMKpXa3BVSXEqTxGzz6GNBp7MFqgdYZ6s8fwjSGlyRCrCvbb1sASbdLR5/e/877Ouvxxo5m09ofGO6mVxv2T5cw7pCfX5FmlTxULzHkwhV20v+okMxxvudtGNuZsVI9L3qZQuJU8mg2q6vPjAsXwtaGKpq760tiQwrQwDH+r2kXHji36Fz6y78Gy5ia7DSHx2KmvKfjZOGlkzWCagDTYaQT8cUiFlDxUfVwE4//lFuklLQRXfWrSJR0DKy23BCeT3ZF/QwmTBUKkPtzlbwjrl8v4kfAHQNO6yif7dt6acIVqjRtT2vqwpP0/MLZ8vPbDrvwNp1lI0qtQUG7HtPNMwixjXD0u21+9aF3uIyGvnGXhf82Ds2GLrUhewLlv5JKCfRL8F53/JzrmWwNs2X4/vNNzEh+hEJ8sXAmT72acqZRkJDeythT/J93z2guz9LDi/3Gxe4fPJYg4E0u8ZzhUPEHdY9VEdK9Z1ycZNaukqF43qt9ZachmrHD8NVZ5qj0jfmwY/9Z0n5tZuJ1ECW2M2Z9SExdemWf/pOJu7odrsxYnnU2t5fOW9iVgh35TYBBZxwnRaLQOM7gQvf4faRcawO1jS1wLLfJEbfDfMQBYao5DK3GyKTS5W9vRqtTqwzg/N44QzrjsOveSTVcQ/Zr7ZOPBosg76IYRe0myCRDvxslxgTDz4mBQ==
    valeur: AgBLcuRi2VKgJNehiPms/9e1S0fFurUtA4/waFC4NmFlZNdYIJbPenO5RBzS0w1j/T5ZKSBk5V/3cSOYMaNhL3pqKid7maUrcftlGQXBWTZSYitXyFEaOf+Uo/4RL/Y0lzHi4jkZaLQCi3ZvhXlu0b/VltI0Swbb2XMkjSGGEy5rH5a52a1ySTrq6g1t5Bv2zr5E4jzPqcJvoR9WbPzGLyaDtdlDON0W6CYxz6OHxjm4ORLRCUdXpSI5i3aS5EeY9C3rrn1D3SCm21MD8CMOUUOS8GIU2yY2MK9rxEBkqDipIwzL0U7QZXRcAtGvPHd6QmBtjEoWxF//bjUI6+zBVrdh3ic5GK10R2jXzlA84XaVHyTGOAqUpxWOSVTolA5C/W0TUhy627UcyeozwbAhi7Z37VYdVn8ZbyKkLdYC4yk+wnypRYjsVULmoIWLa0n2/5ro8/tgjWdoM6mMXM0sreE6i98RuSf6pl3Ns+OkmVvR+jBPk6P3l9bNeNOIQ4dPodvKBgkx/1E9jomKCGHpoo9ZJpUqcl6CrnbiSLfqkuamFs8mufeA7+vIvZaYkrNM499ZVgnXWwZstwW2Zo/AbhYwJKkL5Ue4UxiWD4yWgpJaIpwSTu0k0Ig4d/GW1DeMFH8KwB1YaYIP2k9z5rlWdrlSj4cSIvMkLzDw9wcFkEOuKsGMaa/uiCUGxqd4gkYgV4jZ9+0p0w==
  template:
    metadata:
      name: api-secret
      namespace: rmz2

