apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm-proxy
  namespace: argocd
spec:
  destination:
    namespace: falcon
    name: in-cluster
    namespace: rmz2
  project: default
  source:
    path: ./apps/helm-apps/apps1/
    repoURL: https://github.com/ut0mt8/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
