apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoapi
spec:
  selector:
    matchLabels:
      app: infoapi
  template:
    metadata:
      labels:
        app: infoapi
    spec:
      volumes:
      - name: config
        secret:
          secretName: mysecret
      containers:
      - name: infoapi
        image: ghcr.io/stefanprodan/podinfo:6.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: "/config"
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
