apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-gen
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ut0mt8/gitops/
      revision: HEAD
      directories:
      - path: apps/helm-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      finalizers:
       - resources-finalizer.argocd.argoproj.io
    spec:
      project: falcon
      source:
        repoURL: https://github.com/ut0mt8/gitops/
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
           - values.yaml
      destination:
        name: in-cluster
        namespace: falcon
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
