apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: falcon
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: http://chartmuseum
    targetRevision: 0.1.7
    chart: estimaapi
    helm:
      valueFiles:
        - values.yaml
      values: |
        tag: 1.0.0-e842c23

  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
