apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rmz2
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ./apps/envs/production/testapi/
    repoURL: 'https://github.com/ut0mt8/gitops.git'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




