apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rmz-ns
  namespace: rmz
spec:
  interval: 10m0s
  path: ./apps/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
