apiVersion: v2
name: test-nginx
description: OTS Nginx ingress controller chart

type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: test-nginx
  version: 3.33.0
  repository: https://kubernetes.github.io/ingress-nginx
