apiVersion: v2
name: echotest
description: test helm chart:x

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: echo-server
  version: 0.3.1
  repository: https://ealenn.github.io/charts
