apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoapi
spec:
  selector:
    matchLabels:
      app: infoapi
  template:
    metadata:
      labels:
        app: infoapi
    spec:
      containers:
      - name: infoapi
        image: ghcr.io/stefanprodan/podinfo:6.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
